---
owner: holavonat
repo: instances

sites:
  - name: holavonat.hu
    url: https://holavonat.hu/
  - name: mav-stat.info/map-lite.html
    url: https://mav-stat.info/map-lite.html
  - name: vonatterkep.hu
    url: https://vonatterkep.hu
  - name: ittavonat.eu
    url: https://ittavonat.eu
    assignees:
      - sztupy
  - name: holavonat.is
    url: https://holavonat.is
  - name: holavonat.kinsta.app
    url: https://holavonat.kinsta.app
  - name: holavon.at
    url: https://holavon.at
  - name: hunavonat.hu
    url: http://hunavonat.hu
  - name: megisholavonat.info
    url: https://megisholavonat.info
  - name: map.realtimenext.hu
    url: https://map.realtimenext.hu
  - name: vasutterkep.hu
    url: https://vasutterkep.hu
  - name: whataretheytrainingfor.com
    url: https://whataretheytrainingfor.com/
  - name: kodbazis.hu/holavonat
    url: https://kodbazis.hu/holavonat
  - name: holavonat.mkkp.party
    url: https://holavonat.mkkp.party/
  - name: vonatradar.hu
    url: https://vonatradar.hu
  - name: holakurvavonat.com
    url: https://holakurvavonat.com
  - name: holakurvaanyambavanavonat.hu (mirror list only)
    url:  http://holakurvaanyambavanavonat.hu
  - name: sinenvagyunk.hu
    url: https://sinenvagyunk.hu/
  - name: vonat-keses.hu
    url: https://vonat-keses.hu
  - name: holavonat.serverhu.eu
    url: https://holavonat.serverhu.eu
    assignees:
      - ItsMeSudo
  - name: mennyitkesik.com
    url: https://mennyitkesik.com
status-website:
  cname: holavonat.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: holavonat instance tracker
  baseUrl: /instances
  introTitle: "holavonat instances Upptime Status"
  introDescription: |
    This is a status page for the holavonat instances, powered by Upptime. It monitors the availability and performance of various services related to Hungarian train tracking.
  introMessage: 
    This page is automatically generated by Upptime, a GitHub Action that monitors the status of websites and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

